image: gradle:6.3.0-jdk11

stages:
  - build
  - test
  - publish

before_script:
  - export GRADLE_USER_HOME=.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - gradle assemble --build-cache
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script:
    - gradle check --build-cache

publish:
  stage: publish
  script:
    - gradle publish --build-cache