image: java:8-jdk

stages:
  - build
  - test
  - publish

before_script:
  - export GRADLE_USER_HOME=.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew check

publish:
  stage: publish
  script:
    - ./gradlew publish